[general]
SPECIES_RELEASE_VERSION = 2

[databases]

[ENSEMBL_STYLE]

[EXTERNAL_GENOME_BROWSERS]
EGB_PHY = Phytozome
EGB_CIR = CIRAD

[ENSEMBL_EXTERNAL_URLS]
EGB_PHY = https://phytozome.jgi.doe.gov/jbrowse/index.html?data=genomes/Macuminata&loc=chr###CHR###:###START###..###END###
EGB_CIR = http://jbrowse.southgreen.fr/index.html?data=musa_acuminata_v2&loc=chr###CHR###:###START###..###END###

[ENSEMBL_SPECIES_SITE]

[SPECIES_DISPLAY_NAME]

[ENSEMBL_EXTERNAL_DATABASES]
; DO NOT REMOVE THIS HEADER - defined in DEFAULTS.ini

[ENSEMBL_EXTERNAL_INDEXERS]
; DO NOT REMOVE THIS HEADER - defined in DEFAULTS.ini
