<div class="column-wrapper">
  <div class="column-two">
    <div class="column-left">

      <h2>Overview</h2>

      <p>PanOat is an international pan-genome project for oat where scientists across the world constructed and analysed annotated chromosome-scale 
      reference genome sequences of diverse oat genotypes. The PanOat panel comprises 33 diverse oat lines including 24 cultivars of <i>Avena sativa</i>. 
      The analysis goals include characterization of core gene sets, identifying lineage-specific genes, cataloguing structural variation in wild and 
      domesticated oats, accumulating comparative sequence information for use in agronomic and quality trait mapping, and evolutionary genomic analyses 
      to understand the origin and evolution of oat.</p>

      <h2>Assemblies</h2>

      <p>Out of 24 <i>Avena sativa</i> cultivars, two assemblies were published previously: <a href="https://www.nature.com/articles/s41586-022-04732-y"><i>A. sativa</i> Sang</a> 
      and <a href="https://graingenes.org/GG3/graingenes-downloads/pepsico-oat-ot3098-v2-files-2021"><i>A. sativa</i> OT3098</a>. The genomes of two lines — <i>A. sativa</i> Gehl 
      and <i>A. sativa</i> Nicolas — were sequenced with Illumina short reads. Genome assemblies for Gehl and Nicolas were scaffolded using TRITEX and Hi-C to guide 
      pseudomolecule assembly as described <a href="https://link.springer.com/article/10.1186/s13007-022-00964-1">here</a> and remaining genome sequences 
      were assembled from accurate long reads generated on the PacBio HiFi platform. All contig-level assemblies were scaffolded with chromosome conformation 
      capture (Hi-C) sequencing data.</p>

      <h2>Links</h2>

      <ul>
        <li><a href="https://graingenes.org/GG3/PanOat">PanOat: the oat pangenome project | GrainGenes</a></li>
      </ul>

    </div>
  </div>
  <div class="column-two">
    <div class="column-right">


      <h2>Annotation</h2>

      <p>The genes were annotated using a multi-tiered approach. For the 18 oat cultivars represented here, de novo structural gene prediction, confidence 
      classification and functional annotation were done following a protocol described <a href="https://doi.org/10.1093%2Fplcell%2Fkoab077">here</a>, although 
      differs in the use of TE soft-masked genome sequences instead of TE hints. Gene predictions for the lines <i>A. sativa</i> OT380 (which had no native transcriptome data) 
      was done using a gene consolidation approach that has been described <a href="https://www.nature.com/articles/s41467-025-64046-1">previously</a>. The gene 
      predictions for all the given 19 oat lines were cross-mapped with the genome sequences of one another to identify and correct for missed gene models and to 
      annotate genomes without native transcriptome data. For the remaining three lines <i>A. sativa</i> Leggett, <i>A. sativa</i> Williams and <i>A. sativa</i> AC Morgan, 
      the gene content were predicted using the projection method as described <a href="https://github.com/GeorgHaberer/gene_projection">here</a>.</p>
      <p>Gene annotation provided for <i>Avena sativa</i> OT3098 has previously been done as mentioned 
      <a href="https://graingenes.org/GG3/sites/default/files/data_downloads/PepsiCo_OT3098_V2_panoat_nomenclature_annotation_release notes_0.pdf">here</a> whereas 
      annotation for <i>Avena sativa</i> Sang was derived from <a href="https://graingenes.org/GG3/content/avena-sang-download">here</a>.</p>

      <h2>References</h2>

      <ul>
        <li><a href="https://www.nature.com/articles/s41586-025-09676-7">Avni et al., "A pangenome and pantranscriptome of hexaploid oat", Nature, 2025</a></li>
        <li><a href="https://www.nature.com/articles/s41467-025-57895-3">Bekele et al. "Global genomic population structure of wild and cultivated oat reveals 
          signatures of chromosome rearrangements", Nature Communications, 2025</a></li>
        <li><a href="https://doi.org/10.1038/s41586-022-04732-y">Kamal, N., Tsardakas Renhuldt, N., Bentzer, J. et al. The mosaic oat genome gives insights into 
          a uniquely healthy cereal crop. Nature 606, 113–119 (2022)</a></li>
      </ul>

    </div>
  </div>
</div>
