<div class="column-wrapper">
  <div class="column-two">
    <div class="column-left">

<p>The genome assembly of cultivar Chiifu-401-42 was published on
<a href="https://europepmc.org/abstract/MED/21873998">August 2011</a>
and includes 193 scaffolds orientated and assigned to pseudochromosomes using publicly
available genetic markers.</p>

<p> Gene annotation was conducted using GLEAN and BLAT, with functional annotation inferred 
through similarity to *Arabidopsis thaliana* genes. Repeats were annotated with the 
<a href="https://plants.ensembl.org/info/genome/annotation/repeat_features.html">Ensembl Genomes repeat feature pipeline</a>.
There are: 655,980 Low complexity (Dust) features, covering 33 Mb (11.8% of the genome); 209,256 RepeatMasker features (with the nrplants library), covering 88 Mb (31.1% of the genome); 118,356 RepeatMasker features (with the RepBase library), covering 32 Mb (11.4% of the genome); 145,117 Tandem repeats (TRF) features, covering 14 Mb (4.8% of the genome).</p>

    </div>
  </div>
</div>
