<div class="column-wrapper">
  <div class="column-two">
    <div class="column-left">

      <h2>Overview</h2>

      <p>
        Asian cultivated rice is a staple food for half of the world population. With a
        genome size of ~390 Mb (n=12), rice has the smallest genome among the
        domesticated cereals, making it particularly amenable to genomic studies. In
        2020, a reanalysis of the population structure analysis showed that rice could
        be subdivided into a total of 15 subpopulations (XI-1A, XI-1B1, XI-1B2, XI-2B,
        XI-2A, XI-3B1, XI-3A, XI-3B2, GJ-trop1, GJ-trop2, GJ-subtrp, GJ-tmp, cA2, cA1
        and cB) and 4 admixed populations (GJ-adm, XI-adm, admixed and cA-adm). Then
        16 rice cultivar varieties were selected based on genetic diversity and
        origin that could represent the 15 subpopulations and the largest admixed
        population, i.e. XI-adm. The collection of 16 Platinum Standard RefSeqs
        (PSRefSeq) can be used as a template to detect virtually all standing natural
        variation that exists in the pan-genome of cultivated Asian rice. Oryza
        sativa cv. IRGC 135833 (variety cv. Azucena) (collected from: Philippines) is
        selected as the representative of GJ-trop1 subpopulation, in which the
        accessions are mostly collected from Indonesia, Philippines,
        United States of America, Cote d'Ivoire, and Brazil.
      </p>
      <p>
        Notes of Subpopulations: cA = circum-Aus; cB = circum-Basmati; GJ=
        Geng-japonica where trop = tropical, subtrp = subtropical; XI = Xian-indica
      </p>

      <h4>Assemblies</h4>

      <p>
        Scientists from the University of Arizona, King Abdullah University of
        Science and Technology, International Rice Research Institute, and Huazhong
        Agricultural University generated Oryza sativa cv. IRGC 135833 (variety cv.
        Azucena) genome high quality reference (n=12), which is one of the 16
        PSRefSeqs and represents GJ-trop1 subpopulation.
      </p>
      <p>
        The whole DNA was sequenced by >100 X PacBio Sequel cells. The genome
        assemblies were carried out by multiple assemblers, i.e. mecat2, canu and
        falcon. The pseudomolecule of each chromosome was constructed using the
        nucleotide sequence of multiple assemblies by Genome Puzzle Master by using
        Minghui63 as a guide. The final assembly was polished by >100 X PacBio
        corrected reads and > 100 X Illumina clean reads.
      </p>

      <h4>Annotation</h4>

      <p>
        Done by Ware Lab researchers at Cold Spring Harbor Laboratory. Initial
        protein-coding genes were generated with the MAKER-P pipeline using
        line-specific RNA-seq transcript and full-length transcripts from Zhou et
        al (2020). Non-overlapping ab initio models were added using SNAP,
        Augustus, and FGENESH gene predictors. The combined gene models were
        improved for structure including UTR extensions using line-specific
        full-length transcripts and rice ESTs from GenBank. Final models were
        quality checked using GFF3toolkit and canonical transcripts assigned with
        TRaCE (Olsen and Ware 2020).
      </p>

    </div>
  </div>
  <div class="column-two">
    <div class="column-right">

      <h4>Other resources for viewing the rice pan genome</h4>

      <p>
        The <a href="https://oryza.gramene.org">Gramene Oryza website</a>
        is a genomic and genetic resource supported by USDA-ARS, aimed at
        facilitating advancements in agriculture. The initiative is based at
        Cold Spring Harbor Laboratory, making it a pioneering platform in the
        field. This resource stands out as the first-ever comparative Oryza
        pan-genome resource, harnessing the capabilities of the Ensembl and
        Gramene platforms. Moreover, it is accessible to rice researchers and
        breeders at no cost, enabling them to enhance their efforts in
        developing improved cultivars that possess novel and desirable traits.”
      </p>
      <p>
        The pan genes can also be viewed via the
        <a href="https://riceome.hzau.edu.cn/">Rice Gene Index</a> (RGI). 
      </p>

      <h4>References</h4>

      <ul>
        <li>Yong Zhou, Dmytro Chebotarov, Dave Kudrna, Victor Llaca, Seunghee
        Lee, Shanmugam Rajasekar, Nahed Mohammed, Noor Al-Bader, Chandler
        Sobel-Sorenson, Praveena Parakkal, Lady Johanna Arbelaez, Natalia
        Franco, Nickolai Alexandrov, N. Ruaraidh Sackville Hamilton, Hei Leung,
        Ramil Mauleon, Mathias Lorieux, Andrea Zuccolo, Kenneth McNally,
        Jianwei Zhang & Rod A. Wing<br />
        A platinum standard pan-genome resource that represents the population
        structure of Asian rice<br />
        Scientific Data volume 7, Article number: 113 (2020)</li>
        <li>Yu Z, Chen Y, Zhou Y, Zhang Y, Li M, Ouyang Y, Chebotarov D,
        Mauleon R, Zhao H, Xie W, McNally K, Wing R, Guo W and Zhang J.<br />
        Rice Gene Index: A comprehensive pan-genome database for comparative
        and functional genomics of Asian rice.<br />
        Molecular Plant, 2023, 16(5):798-801</li>
        <li>Andrew J Olson, Doreen Ware<br />
        Ranked choice voting for representative transcripts with TRaCEM<br/ >
        Bioinformatics, Volume 38, Issue 1, January 2022, Pages 261–264</li>
      </ul>

    </div>
  </div>
</div>
