<div class="column-wrapper">
  <div class="column-two">
    <div class="column-left">

<h2>Overview</h2>

<p>The <a href="http://www.10wheatgenomes.com/10-wheat-genomes-project-and-the-wheat-initiative">10+ Wheat Genomes Project</a> 
is a global partnership that leverages collaborative expertise and funding with the aim to 
characterise the wheat pan-genome. Created in 2011 following endorsement from the G20 
Agriculture Ministries, the Wheat Initiative provides a framework to establish strategic 
research and organization priorities for wheat research at the international level in both 
developed and developing countries. Seeds of all cultivars included in the project can be 
ordered for research use through the Germplasm Resources Unit at the John Innes Centre, UK. 
This also includes additional info about country source and sowing season. Please visit the 
<a href="https://www.seedstor.ac.uk/search-browseaccessions.php?idCollection=35">SeedStor</a> for
more information.</p>

<h4>10+ Wheat Genome Lines</h4>

<p>The 10+ Wheat Genome Project has completed its goal of generating chromosome pseudomolecule 
assemblies for 10 wheat cultivars and 5 scaffold assemblies. These cultivars were selected by 
each of the global partners to represent genetic diversity typical of breeding programs in 
their agroecological zones. Genome sequences have been assembled to reference quality using 
the NRgene DeNovo Magic 3.0 software for pseudomolecule assemblies.</p>

    </div>
  </div>
  <div class="column-two">
    <div class="column-right">

<h4>UK Wheat Lines</h4>

<p>Five wheat lines chosen for their importance in breeding and research in the United Kingdom 
have been sequenced and displayed in Ensembl as part of our contribution to the Designing Future 
Wheat project. This includes Claire, Cadenza, Paragon, Robigus and Weebill.</p>

<p>These scaffold-level assemblies were sequenced at the Earlham Institute as part of the 
wheat pan genome. Sequencing was performed on an Illumina HiSeq 2500 instrument with a 
2x250 bp read metric targeting 45x raw coverage of the amplification-free library and 
25x coverage of a combination of mate-pair libraries with inserts sizes &gt;7 Kbp. Between 
44 and 51x paired-end genome coverage was generated per line. Contigging was performed using 
the w2rap-contigger using k=200. Two mate-pair libraries were produced for each line except 
Weebill, where five libraries were used. Mate-pairs were processed, filtered and used to 
scaffold contigs as described in the w2rap pipeline. Scaffolds less than 500bp were removed 
from the final assemblies. The K-mer Analysis Toolkit was used to validate scaffolds by 
generating a kmer histogram from the matrix of kmers shared between the paired-end reads and 
the scaffolds.</p> 

<ul>
  <li>Walkowiak, S., Gao, L., Monat, C. et al. Multiple wheat genomes reveal global variation 
in modern breeding. Nature (2020). <a href="https://doi.org/10.1038/s41586-020-2961-x">https://doi.org/10.1038/s41586-020-2961-x</a></li>
</ul>

    </div>
  </div>
</div>
<div>
<div class="column-wrapper">
  <div class="column-two">
    <div class="column-left">

<h2>Genes</h2>

<p>Genes have been projected for all assemblies from the IWGSC RefSeq v1.1 annotation. 
<i>De novo</i> gene annotation is currently being worked on and will be added at a later stage.</p>
<ul>
  <li><a href="https://webblast.ipk-gatersleben.de/downloads/wheat/gene_projection/readme_10WheatProjections.txt">More information about the projection</a></li>
  <li><a href="https://webblast.ipk-gatersleben.de/downloads/wheat/gene_projection/geneid_2_chinese.sourceid.txt">Download gene mapping</a> from the reference to the rest of the cultivars</li>
</ul>

    </div>
  </div>
</div>
