<div class="column-wrapper">
  <div class="column-two">
    <div class="column-left">

<h2>UK Wheat Lines</h2>

<p>Five wheat lines chosen for their importance in breeding and research in the United Kingdom 
have been sequenced and displayed in Ensembl as part of our contribution to the Designing Future 
Wheat project. This includes Claire, Cadenza, Paragon, Robigus and Weebill.</p>

<p>These scaffold-level assemblies were sequenced at the Earlham Institute as part of the 
wheat pan genome. Sequencing was performed on an Illumina HiSeq 2500 instrument with a 
2x250 bp read metric targeting 45x raw coverage of the amplification-free library and 
25x coverage of a combination of mate-pair libraries with inserts sizes &gt;7 Kbp. Between 
44 and 51x paired-end genome coverage was generated per line. Contigging was performed using 
the w2rap-contigger using k=200. Two mate-pair libraries were produced for each line except 
Weebill, where five libraries were used. Mate-pairs were processed, filtered and used to 
scaffold contigs as described in the w2rap pipeline. Scaffolds less than 500bp were removed 
from the final assemblies. The K-mer Analysis Toolkit was used to validate scaffolds by 
generating a kmer histogram from the matrix of kmers shared between the paired-end reads and 
the scaffolds.</p> 

<ul>
  <li>Walkowiak, S., Gao, L., Monat, C. et al. Multiple wheat genomes reveal global variation 
in modern breeding. Nature (2020). <a href="https://doi.org/10.1038/s41586-020-2961-x">https://doi.org/10.1038/s41586-020-2961-x</a></li>
</ul>

<p>Genes were projected for all assemblies from the IWGSC RefSeq v1.1 annotation. <i>De novo</i> 
gene annotation is currently being worked on and will be added at a later stage.
For the cultivar Stanley in chromosome 2A some genes need to be reloaded; you can find 
more details on our <a href="http://www.ensembl.info/known-bugs/ensembl-103/">known bugs page</a>.</p>

    </div>
  </div>
</div>
